theme: minima
name: Data Privacy Course (Undergraduate Level), UVA, Fall 2022
title: null
author:
  name: Tianhao Wang
  email: "tianhao@virginia.edu"
header_pages:
  - assignments.md
  - project.md
  - policy.md
